pretrained_model_path: 'stablediffusionapi/rev-animated' 
output_dir: ""    # "./outputs/v1_demo/pose/dance"
pretrained_controlnet_path: "/mnt/data/users/haiming.zhu/weight/sd-controlnet-hed/"
# pretrained_controlnet_path: "/private/workspace/zhm/sd/control_v11p_sd15_softedge/"

control_config:
  type: "hed"
  # type: "canny"
  low_threshold: 50
  high_threshold: 100
  control_scale: 0.95
  unet_subfolder: "flat"

train_data:
  video_path: "videos/greetingfox_input.mp4"
  prompt: "A man walks on the mountain carrying a guitar"
  n_sample_frames: 16
  width: 512
  height: 512


validation_data:
  prompts:
    - "Greetings from a dog by shaking front paws, cartoon style"
  video_length: 600
  width: 512
  height: 512
  guidance_scale: 7.5  # sd原版推荐12，moxin是3.2， 其他推荐7.5
  num_steps: 50
  start: "noise"
  edit_type: "DDIM"
  sample_start_idx: 0
  sample_frame_rate: 1

learning_rate: 3e-5
train_batch_size: 1
max_train_steps: 300
validation_steps: 100
trainable_modules:
  - "attn1.to_q"
  - "attn2.to_q"
  - "attn_temp"
  - "norm_temp"
  - "conv_temp"

seed: 0
mixed_precision: fp16
gradient_checkpointing: True
enable_xformers_memory_efficient_attention: True