pretrained_model_path: "/private/workspace/zhm/sd/stable-diffusion-v1-5/"
output_dir: ""    # "./outputs/v1_demo/pose/dance"
pretrained_controlnet_path: "/private/workspace/zhm/sd/sd-controlnet-hed/"
# pretrained_controlnet_path: "/private/workspace/zhm/sd/control_v11p_sd15_softedge/"
# 只适合粗糙mask
# 在rgb_flow_warp_kv不适合对levle=4进行：一直存在的区域 设置
# 对query和kv的warp只要2 1的level，level=4不进行warp
control_config:
  type: "hed"
  control_scale: 0.7
  unet_subfolder: "unet"

train_data:
  video_path: ""
  prompt: "A handsome man in a suit and tie"
  n_sample_frames: 60
  width: 512
  height: 512
  sample_start_idx: 0
  sample_frame_rate: 1

validation_data:
  prompts:
    - "Disney style, a man, in a castle"
  video_length: 60
  width: 512
  height: 512
  guidance_scale: 7.5  # sd原版推荐12，moxin是3.2， 其他推荐7.5
  num_steps: 50
  start: "noise"
  edit_type: "DDIM"

learning_rate: 3e-5
train_batch_size: 1
max_train_steps: 300
validation_steps: 100
trainable_modules:
  - "attn1.to_q"
  - "attn2.to_q"
  - "attn_temp"
  - "norm_temp"
  - "conv_temp"

seed: 0
mixed_precision: fp16
gradient_checkpointing: True
enable_xformers_memory_efficient_attention: True